# -*- coding: utf-8 -*-
"""ZeroTrace

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u0KrKIpZ3asgVZ4YqShAN0mh_eHzDSB_

# Install Libraries
"""

!pip install cryptography rsa

"""# Import Libraries"""

import os
import base64
import hashlib
import rsa
import secrets
import time

from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives.padding import PKCS7
from cryptography.hazmat.backends import default_backend

"""# Generate Anonymous ID (Novel Feature)"""

def generate_anonymous_id():

    anonymous_id = secrets.token_hex(8)

    print("Anonymous ID Generated:", anonymous_id)

    return anonymous_id

"""# Generate AES-256 Key"""

def generate_aes_key():

    key = os.urandom(32)

    print("AES-256 Key Generated")

    return key

"""# AES Encryption"""

def aes_encrypt(message, key):

    iv = os.urandom(16)

    padder = PKCS7(128).padder()
    padded = padder.update(message.encode()) + padder.finalize()

    cipher = Cipher(
        algorithms.AES(key),
        modes.CBC(iv),
        backend=default_backend()
    )

    encryptor = cipher.encryptor()

    ciphertext = encryptor.update(padded) + encryptor.finalize()

    encrypted = base64.b64encode(iv + ciphertext).decode()

    print("Message Encrypted using AES-256")

    return encrypted

"""# AES Decryption"""

def aes_decrypt(ciphertext, key):

    data = base64.b64decode(ciphertext)

    iv = data[:16]
    encrypted = data[16:]

    cipher = Cipher(
        algorithms.AES(key),
        modes.CBC(iv),
        backend=default_backend()
    )

    decryptor = cipher.decryptor()

    padded = decryptor.update(encrypted) + decryptor.finalize()

    unpadder = PKCS7(128).unpadder()

    message = unpadder.update(padded) + unpadder.finalize()

    print("Message Decrypted using AES-256")

    return message.decode()

"""# SHA-256 Integrity (Novel Tamper Detection)"""

def generate_hash(message):

    hash_value = hashlib.sha256(message.encode()).hexdigest()

    print("SHA-256 Hash Generated")

    return hash_value

"""# RSA Key Generation"""

def generate_rsa_keys():

    public_key, private_key = rsa.newkeys(2048)

    print("RSA Keys Generated")

    return public_key, private_key

"""# Encrypt AES Key using RSA"""

def rsa_encrypt_key(aes_key, public_key):

    encrypted = rsa.encrypt(aes_key, public_key)

    encoded = base64.b64encode(encrypted).decode()

    print("AES Key Encrypted using RSA")

    return encoded

"""# Decrypt AES Key"""

def rsa_decrypt_key(encrypted_key, private_key):

    decoded = base64.b64decode(encrypted_key)

    key = rsa.decrypt(decoded, private_key)

    print("AES Key Decrypted using RSA")

    return key

"""# Secret Sharing (Novel Group Security)"""

def generate_group_key():

    key = secrets.randbits(128)

    print("Group Key Generated:", key)

    return key


def split_group_key(group_key, members=5):

    shares = []

    for i in range(members-1):
        shares.append(secrets.randbits(128))

    last = group_key

    for share in shares:
        last ^= share

    shares.append(last)

    print("Group Key Split into Shares")

    return shares


def reconstruct_group_key(shares):

    key = 0

    for share in shares:
        key ^= share

    print("Group Key Reconstructed")

    return key

"""# Sender Side Simulation"""

print("\n SENDER SIDE ")

message = input("Enter Message: ")

anonymous_id = generate_anonymous_id()

aes_key = generate_aes_key()

encrypted_message = aes_encrypt(message, aes_key)

hash_value = generate_hash(message)

public_key, private_key = generate_rsa_keys()

encrypted_key = rsa_encrypt_key(aes_key, public_key)

group_key = generate_group_key()

group_shares = split_group_key(group_key)

message_package = {

    "anonymous_id": anonymous_id,
    "encrypted_message": encrypted_message,
    "hash": hash_value,
    "encrypted_key": encrypted_key,
    "group_shares": group_shares,
    "timestamp": time.time()
}

print("\nSecure Message Package Created")

"""# Receiver Side Simulation"""

print("\n RECEIVER SIDE ")

received_key = rsa_decrypt_key(
    message_package["encrypted_key"],
    private_key
)

decrypted_message = aes_decrypt(
    message_package["encrypted_message"],
    received_key
)

new_hash = generate_hash(decrypted_message)

if new_hash == message_package["hash"]:

    print("\nIntegrity Verified")
    print("Message:", decrypted_message)

else:

    print("Tampering Detected")

recovered_group_key = reconstruct_group_key(
    message_package["group_shares"]
)

print("Recovered Group Key:", recovered_group_key)

"""# Self-Destruct Feature (Novel Feature)"""

print("\nMessage will self-destruct in 5 seconds")

time.sleep(5)

decrypted_message = None

print("Message deleted securely")